# Generated by Django 5.2.7 on 2025-11-05 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('skin_tone', models.CharField(blank=True, choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('tan', 'Tan'), ('olive', 'Olive'), ('brown', 'Brown'), ('dark', 'Dark')], max_length=20, null=True)),
                ('body_shape', models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('hourglass', 'Hourglass'), ('pear', 'Pear'), ('apple', 'Apple'), ('inverted_triangle', 'Inverted triangle')], max_length=20, null=True)),
                ('face_shape', models.CharField(blank=True, choices=[('oval', 'Oval'), ('round', 'Round'), ('square', 'Square'), ('heart', 'Heart'), ('diamond', 'Diamond'), ('oblong', 'Oblong')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('beige', 'Beige'), ('brown', 'Brown'), ('pink', 'Pink'), ('purple', 'Purple'), ('other', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('dress', 'Dress'), ('suit', 'Suit'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
